name: Main

on: push

jobs:
  # codestyle:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Rust
  #       uses: hecrj/setup-rust-action@v1
  #       with:
  #         components: rustfmt
  #         rust-version: nightly
  #     - uses: actions/checkout@v2
  #     - run: cargo fmt --all -- --check

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Rust
  #       uses: hecrj/setup-rust-action@v1
  #       with:
  #         components: clippy
  #     - uses: actions/checkout@v2
  #     - run: cargo clippy --all-targets -- -D clippy::all

  # compile:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Rust
  #       uses: hecrj/setup-rust-action@v1
  #     - uses: actions/checkout@v2
  #     - run: cargo check --all

  test:
    #needs: [codestyle, lint, compile]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
    - name: Install matcher
      run: echo "::add-matcher::.github/rust.json"
    - name: Test
      run: cargo test